# Generated by Django 2.2.4 on 2019-08-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='ShadowHand',
            fields=[
                ('recruit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recruitment.Recruit')),
                ('sith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Sith')),
            ],
            bases=('recruitment.recruit',),
        ),
    ]
