# Generated by Django 2.2.4 on 2019-08-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='shadow_handed',
            field=models.BooleanField(default=False),
        ),
    ]
