# Generated by Django 2.2.4 on 2019-08-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrialQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('question', models.TextField()),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trials.Trial')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trials.TrialQuestion')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Recruit')),
            ],
        ),
    ]
