# Generated by Django 2.2.4 on 2019-08-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitanswer',
            options={'ordering': ('question__order',)},
        ),
        migrations.AlterModelOptions(
            name='trialquestion',
            options={'ordering': ('order',)},
        ),
    ]
