# Generated by Django 2.2.4 on 2019-08-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruit_shadow_handed'),
        ('trials', '0002_auto_20190815_1907'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recruitanswer',
            unique_together={('recruit', 'question')},
        ),
    ]
